[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.docs]
description = "Builds the rustdocs for the full crate"
command = "cargo"
toolchain = "nightly"
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
args = ["doc", "--no-deps", "--all-features"]

[tasks.license]
description = "Add license notices to source files"
install_crate = "add-notice"
command = "add-notice"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
toolchain = "nightly"
args = ["fmt", "--", "--emit=files"]

[tasks.check_format]
install_crate = "rustfmt"
command = "cargo"
toolchain = "nightly"
args = ["fmt", "--", "--check"]
