name: Feature Request
description: File a feature request if you have a suggestion for a new feature.
title: "feat: "
labels: [ "type: feature request" ]
body:
  - type: markdown
    attributes:
      value: |
        A good feature request ideally
        * is either immediately obvious, or
        * starts with a use case that is not achievable with the existing
          API and includes a brief API proposal that would make the use
          case possible.
  - type: textarea
    attributes:
      label: Description
      description: |
        Describe the feature request. Provide the following:
            1. Use case
            2. How the project _currently_ handles it
            3. How you propose the project _should_ handle it
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: API Proposal
      description: |
        If your feature request requires API changes, describe the changes and the
        new API's signature and usage.
    validations:
      required: false
